name: Update Flatpak Manifest

on:
  push:
  workflow_dispatch:

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v4

    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        repository: lkavindu199/test_libre
        token: ${{ secrets.TARGET_REPO_TOKEN }}
        path: target-repo

    - name: Get latest commit
      id: commit-info
      run: |
        echo "latest_commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Update manifest with Python
      run: |
        cd target-repo

        LATEST_COMMIT="${{ steps.commit-info.outputs.latest_commit }}"

        python3 -c "
        # Read file
        with open('rocks.poopjournal.librelinkupdesktop.yml', 'r') as f:
            content = f.read()

        # Replace URL
        if 'deviitorinc/LibreLinkUpDesktop.git' in content:
            content = content.replace(
                'url: https://github.com/deviitorinc/LibreLinkUpDesktop.git',
                'url: https://github.com/lkavindu199/LibreLinkUpDesktop_new1.git'
            )
            print('✅ Updated URL')
        else:
            print('⚠️  deviitorinc URL not found')

        # Replace branch (any branch name)
        import re
        content = re.sub(
            r'(url: https://github\.com/lkavindu199/LibreLinkUpDesktop_new1\.git\s+)branch: \S+',
            r'\\1branch: main',
            content
        )
        print('✅ Updated branch to main')

        # Replace commit (any commit hash)
        content = re.sub(
            r'(branch: main\s+)commit: [a-f0-9]+',
            r'\\1commit: $LATEST_COMMIT',
            content
        )
        print('✅ Updated commit ID')

        # Write back
        with open('rocks.poopjournal.librelinkupdesktop.yml', 'w') as f:
            f.write(content)
        "

    - name: Commit and push
      run: |
        cd target-repo
        git config user.name "GitHub Actions Bot"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git add rocks.poopjournal.librelinkupdesktop.yml

        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "chore: Auto-update manifest with latest source"
          git push
          echo "✅ Manifest updated successfully"
        fi
