name: Update Flatpak Manifest

on:
  push:
  workflow_dispatch:

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v4

    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        repository: lkavindu199/test_libre
        token: ${{ secrets.TARGET_REPO_TOKEN }}
        path: target-repo

    - name: Get latest commit
      id: commit-info
      run: |
        echo "latest_commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        echo "Commit to use: ${{ steps.commit-info.outputs.latest_commit }}"

    - name: Update manifest with exact replacements
      run: |
        cd target-repo

        # Use a simple Python script for exact replacements
        python3 << "EOF"
        # Read the entire file
        with open('rocks.poopjournal.librelinkupdesktop.yml', 'r') as f:
            content = f.read()

        # Make the exact replacements
        content = content.replace(
            'url: https://github.com/deviitorinc/LibreLinkUpDesktop.git',
            'url: https://github.com/lkavindu199/LibreLinkUpDesktop_new1.git'
        )
        content = content.replace(
            "branch: feature/trayicon",
            "branch: main"
        )
        content = content.replace(
            "commit: e7e51178e018d06932ac773d8b28d3ee44ab1ef4",
            "commit: ${{ steps.commit-info.outputs.latest_commit }}"
        )

        # Write back
        with open('rocks.poopjournal.librelinkupdesktop.yml', 'w') as f:
            f.write(content)

        print("✅ File updated successfully")
        EOF

    - name: Commit and push changes
      run: |
        cd target-repo
        git config user.name "GitHub Actions Bot"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git add rocks.poopjournal.librelinkupdesktop.yml

        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "chore: Update manifest to point to main repo commit ${{ steps.commit-info.outputs.latest_commit }}"
          git push
          echo "✅ Successfully updated manifest"
        fi
