name: Update Flatpak Manifest

on:
  push:
  workflow_dispatch:

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v4

    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        repository: lkavindu199/test_libre
        token: ${{ secrets.TARGET_REPO_TOKEN }}
        path: target-repo

    - name: Get latest commit info from source repo
      id: commit-info
      run: |
        LATEST_COMMIT=$(git rev-parse HEAD)
        COMMIT_DATE=$(git log -1 --format=%cd --date=short)
        echo "latest_commit=$LATEST_COMMIT" >> $GITHUB_OUTPUT
        echo "commit_date=$COMMIT_DATE" >> $GITHUB_OUTPUT
        echo "Latest commit: $LATEST_COMMIT"
        echo "Commit date: $COMMIT_DATE"

    - name: Update Flatpak manifest
      run: |
        cd target-repo

        # Update the YAML file with new commit ID and URL
        python3 << 'EOF'
        import yaml
        import sys

        # Read the current manifest
        with open('rocks.poopjournal.librelinkupdesktop.yml', 'r') as file:
            manifest = yaml.safe_load(file)

        # Find the librelinkupdesktop module and update it
        for module in manifest['modules']:
            if module['name'] == 'librelinkupdesktop':
                # Update git source URL and commit
                for source in module['sources']:
                    if source.get('type') == 'git' and 'librelinkupdesktop' in source.get('url', ''):
                        source['url'] = 'https://github.com/lkavindu199/LibreLinkUpDesktop_new1.git'
                        source['branch'] = 'main'
                        source['commit'] = '${{ steps.commit-info.outputs.latest_commit }}'
                        break
                break

        # Write the updated manifest back
        with open('rocks.poopjournal.librelinkupdesktop.yml', 'w') as file:
            yaml.dump(manifest, file, default_flow_style=False, sort_keys=False, width=1000)

        print("✅ Successfully updated Flatpak manifest")
        EOF

    - name: Verify changes
      run: |
        cd target-repo
        echo "Updated file content:"
        cat rocks.poopjournal.librelinkupdesktop.yml | grep -A 5 -B 5 "librelinkupdesktop"

    - name: Commit and push changes
      run: |
        cd target-repo
        git config user.name "GitHub Actions Bot"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git add rocks.poopjournal.librelinkupdesktop.yml

        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "chore: Update Flatpak manifest with latest commit ${{ steps.commit-info.outputs.latest_commit }} from main repo"
          git push
          echo "✅ Manifest updated and pushed successfully"
        fi
